### ISSUE TITLE
unable to view all of my playlists

### ISSUE THREAD

**Issue by eastblue056** [maxrave-dev/SimpMusic#1032]
**Bug Summary**

Playlist section is being displayed in horizontal scroll instead of vertical list, making it impossible to access all imported playlists (3000+ songs across multiple playlists transferred from Spotify via TuneMyMusic).

**Environment**

App Version: v0.2.16

Device: Samsung Galaxy S20+

Android Version: 13

Playlist Count: Multiple playlists (~3000 songs total)

**Steps to Reproduce**

- Import large number of playlists via YouTube Music (transferred from Spotify using TuneMyMusic)

- Open SimpMusic and navigate to playlist section

- Observe playlist display format

**Expected vs Actual Behavior**

Expected: Playlists displayed in vertical scrollable list format

Actual: Playlists displayed horizontally, requiring horizontal scrolling to access different playlists, with some playlists remaining inaccessible

**Additional Information**

Issue persists after logging out/in

Problem continues despite being on latest version (v0.2.16)

Recent playlist fixes in v0.2.15 did not resolve this specific UI layout issue

**Screenshots**

- below I attached Screenshots from simpmusic and how playlists are being displayed in other apps (dedicated playlist page with filtering & sort options) 

![Image](https://github.com/user-attachments/assets/ad02f7af-3e73-49bb-827c-e627fe640a23)

![Image](https://github.com/user-attachments/assets/3b6df341-1a63-4b75-be56-d23f06d60c7c)

![Image](https://github.com/user-attachments/assets/adfb0964-573d-40a2-9b8c-68ca598e3f83)
![Image](https://github.com/user-attachments/assets/57d6bca7-ba4c-4a75-a7fd-973f921ad740)

**Comment by maxrave-dev** [comment]
The YouTube Music Playlist section does not show full of your playlist? Can you help me check the max number of the playlist which the app can show?

**Comment by eastblue056** [comment]
> The YouTube Music Playlist section does not show full of your playlist? Can you help me check the max number of the playlist which the app can show?


Yes that's correct. There's no option for me to expand the playlists and view all of them. I just checked and the app shows 24 playlists.

**Comment by maxrave-dev** [comment]
ok, i will research more

**Comment by maxrave-dev** [comment]
Fixed in latest build

**Comment by eastblue056** [comment]
Hey thank you for your response.

I just updated the app to v0.2.18-hf and all of my playlists are still not visible for me. (first screenshot) 

I noticed the app already has a "more" button for the albums and videos sections (second screenshot).

is it be possible to also add a  "more" button to the "your youtube playlists" section? 

I think this would help users view all their playlists without a huge UI redesign. 

Thanks in advance! 

![Screenshot_20250724_213237_SimpMusic.jpg](https://github.com/user-attachments/assets/63ae1c35-4695-49ae-a829-b102e6998540)


![Screenshot_20250724_212937_SimpMusic.jpg](https://github.com/user-attachments/assets/e332c00c-e353-45f5-ac6d-9c4de9e75c6c)
