### ISSUE TITLE
playback in Android Auto

### ISSUE THREAD

**Issue by GruNostalgia** [maxrave-dev/SimpMusic#1095]
I'm on 2.18-hf
Audio will not play through Android Auto...
Works fine on the device and I'm able to play music through other music apps in Android Auto fine. I'm wondering if I'm missing something here? I tried googling but maybe not well enough. Thanks.

**Describe the bug**

Steps 
Phone connects to vehicle through Android Auto
Open simpmusic on phone
Play a song
Song starts to play (visually see the bar slider) but no audio

**Comment by davideroma** [comment]
Ho lo stesso identico problema ho provato anche con altre app simili è la stessa cosa....ma se tieni aperto YouTube allora funziona

**Comment by dam00042** [comment]
I'm having the same issue. I thought it was only me but it seems to be a common error since last version was released.

**Comment by davideroma** [comment]
Comunque se fai partire una canzone qualsiasi su YouTube e lo tieni aperto in background a quel punto apri simpmusic e fai partire una canzone o una tua playlist a quel punto funziona

**Comment by GruNostalgia** [comment]
I translated davideroma's message with google translate and I got this "However, if you start any song on YouTube and keep it open in the background at that point open simpmusic and start a song or your own playlist at that point it works"

This is an interesting work around. I will try this after work, I wonder what is causing the behavior to not work from simp music itself..

**Comment by dam00042** [comment]
Yeah but for me, it's not intuitive or convenient to have to open another app every time I want to listen to music on Android Auto. I just want to connect my phone to the car and have it start playing without any problems.

**Comment by giovannitrano** [comment]
I had the same problem. I uninstalled and went back to the previous version 0.2.17

This seems to be a bug with the latest version 0.2.18

**Comment by Allzweck** [comment]
I have the same bug. Workaround is to switch back to 0.2.18 or start any other audio app. I tried it with Audible, then you have both audios, then pause Audible and SimpMusic works. But if you close and open again, it is again muted.

**Comment by Quasardian** [comment]
Same bug for me, quite unusable when you want to start driving.
I see many bugs with android auto.
I think most of them are already mentioned on Github or in the Discord.
@maxrave-dev Mention me if you need testing on Android Auto.

**Comment by maxrave-dev** [comment]
I think I know something, please wait for me

**Comment by maxrave-dev** [comment]
A trick is clicking to the voice button (Google Assistant) and the sound is playing again
OR open YouTube Music and play from YouTube Music,  the SimpMusic is playing again, then pause YouTube Music

**Comment by davideroma** [comment]
Si il trucco di YouTube lo conoscevo mentre quello dell' assistente vocale no .... grazie

**Comment by spkemob** [comment]
> A trick is clicking to the voice button (Google Assistant) and the sound is playing again OR open YouTube Music and play from YouTube Music, the SimpMusic is playing again, then pause YouTube Music

if start the Assistant the music stops after short time ( and the quality is very bad ), also if I use the maps navigation the music start every time the voice give you an instruction.

 I find the trick before reading this tread.. start playing Google news directly from android auto and it works untill you disconnect.
sorry for my bad English!
grazie

**Comment by maxrave-dev** [comment]
Please use nightly build, I fixed it

**Comment by Quasardian** [comment]
Yes that fixed the not audio playing issue on Android Auto.
I still have a problem that audio stops after like a minute.
Something like source error or source unavailable.
Almost seems like YT is trying to play an ad which crashes the app.

**Comment by CrazyWolf13** [comment]
This is fixed :)
