### ISSUE TITLE
UI bug: Button without text and truncated Russian translation

### ISSUE THREAD

**Issue by lony-official** [maxrave-dev/SimpMusic#1320]
**Describe the bug**
There are two UI issues in the app interface:
1. One button is displayed without any text.
2. The Russian translation for the “Show” button is cut off — instead of the full word “Показать”, only “Пока” is visible in the app.

The translation string can be found [here](https://github.com/maxrave-dev/SimpMusic/blob/102873073f8ccdcd4d1db93d9dcf9ff79dd1ab94/core/common/src/main/res/values-ru/strings.xml#L19)

**To Reproduce**
Open the app with Russian language selected.
Go to the screen shown in the attached screenshots.
Observe that one button has no text, and another shows the truncated translation “Пока”.

**Expected behavior**
The buttons should display their labels correctly in all languages.
In the Russian version, the full text “Показать” should be visible.
Alternatively, an icon could be used instead of text to prevent truncation and improve UI consistency.

**App Version**
SimpMusic v0.2.21

Screenshot 1: button without text

![Image](https://github.com/user-attachments/assets/77fdb7de-1935-4e7e-8d4e-0db0e3c1844c)

Screenshot 2: truncated Russian label (“Пока”) and icon suggestion

![Image](https://github.com/user-attachments/assets/169aa7b9-7c26-4e77-99aa-87eb78dcdcb4)

**Log (Error Details)**
Not applicable — this is a UI display issue, not a crash.

**Comment by maxrave-dev** [comment]
I fixed, thanks bro, checked nightly version<br>https://simpmusic.org/nightly-download

**Comment by lony-official** [comment]
> Я исправил, спасибо, бро, проверил ночную версию https://simpmusic.org/nightly-download

I downloaded the nightly version, but the errors are still there. I tried deleting the app and reinstalling it, but that didn’t help.
nightly version 0.2.21

**Comment by maxrave-dev** [comment]
try to download again, may be you download the build which is not latest
