### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Hwezah** [maxrave-dev/SimpMusic#632]
**Describe the bug***
1. Miss aligned play/pause center button when 
Lyrics are viewed in full mode.
2. I feel the lyrics/metadata column could have
been a little wider.
3. I also wish the app incorperated the feature to use the app to play locally stored songs on the device as a normal player
4. Also, the app loses network connection and I have to clear cache and storage to restore it.
5. I also wish it could download the songs to local storage
.....Im using the galaxy S20

**To Reproduce**
1. Go to ..search song to play
3. Click on the desired song, then tap on the playing bar at the bottom to open the player in full mode.
6. Scroll up to reveal the Lyrics section, then tap to see Lyrics in full mode.
7. See error

***Expected behavior***
The center/play button should be correctly alighed center
The play/pause, skip,shuffle,repeat controls could be a notch smaller.
The Lyrics&Metadata section(column) when viewed in full, could be a notch wider

**Screenshots**

**Log (Error Details)**
Paste the log from the crashing screen, if it is not a crash bug, skip it.

**Comment by Hwezah** [comment]
![Screenshot_20241220_193316_SimpMusic](https://github.com/user-attachments/assets/1844ce18-74b1-4c68-822f-7f2f3ff0bfb9)
![Screenshot_20241220_193022_SimpMusic](https://github.com/user-attachments/assets/6702a42f-7782-4281-b367-c0580da42f3f)

**Comment by RounakDadsena** [comment]
Lyrics buttons already fixed in latest commit

**Comment by Hwezah** [comment]
Thanks...Update fixed the Centering of the play/pause button.
...Update didn't fix the internet connection though. I just wonder how the UI shows up well  but when you try to play a song 6/10 times it fails...Error says: Time out, check your internet  connection 🤔
